export const IDS = {
  CRUCIBLE: {
    WINDOW_ROOT: "cr-root",
    NODES_COL: "cr-nodes-col",
    PHASE_TEXT: "cr-phase",
    INTENT_TEXT: "cr-intent",
    STRATEGY_TEXT: "cr-strategy",
    START_BTN: "cr-start-btn",
    STOP_BTN: "cr-stop-btn",
    GOALS_BTN: "cr-goals-btn",
    SOLVE_BTN: "cr-solve-btn",
    STATUS_TEXT: "cr-status",
    PRUNE_BTN: "cr-prune-btn",
    COMMIT_BTN: "cr-commit-btn",
    RESET_BTN: "cr-reset-btn",
    EMPTY_STATE: "cr-empty",
    ADD_GOAL_BTN: "cr-add-goal-btn",
    ADD_NODE_BTN: "cr-add-node-btn",
    KIND_ROW: "cr-kind-row",
    node: (id: string) => ({
      ROOT: `cr-node-${id}`,
      CONTENT: `cr-node-${id}-content`,
      CONTENT_INPUT: `cr-node-${id}-input`,
      ACTIONS: `cr-node-${id}-actions`,
      VIEW: `cr-node-${id}-view`,
      EDIT: `cr-node-${id}-edit`,
      STALE: `cr-node-${id}-stale`,
      SAVE_BTN: `cr-node-${id}-save`,
      CANCEL_BTN: `cr-node-${id}-cancel`,
      CONNECTIONS: `cr-node-${id}-connections`,
      NAME: `cr-node-${id}-name`,
    }),
    kindSection: (kind: string) => `cr-kind-section-${kind}`,
  },
  BRAINSTORM: {
    ROOT: "se-bs-root",
    LIST: "se-bs-list",
    INPUT: "se-bs-input",
    SEND_BTN: "se-bs-send-btn",

    message: (id: string) => ({
      ROOT: `se-bs-msg-${id}`,
      VIEW: `se-bs-msg-${id}-view`,
      EDIT: `se-bs-msg-${id}-edit`,
      TEXT: `se-bs-msg-${id}-text`,
      INPUT: `se-bs-msg-${id}-input`,
    }),
  },
  LOREBOOK: {
    PANEL: "kse-lorebook-panel",
    CONTAINER: "lb-container",
    EMPTY_STATE: "lb-empty-state",
    NOT_MANAGED: "lb-not-managed",
    MAIN_CONTENT: "lb-main-content",
    ENTRY_NAME: "lb-entry-name",
    CONTENT_INPUT: "lb-content-input",
    KEYS_INPUT: "lb-keys-input",
    GEN_CONTENT_BTN: "lb-gen-content-btn",
    GEN_KEYS_BTN: "lb-gen-keys-btn",
    REFINE_BTN: "lb-refine-btn",
    REFINE_INSTRUCTIONS_INPUT: "lb-refine-instructions",

    // Storage keys for streaming drafts
    // Raw keys for storyStorage.set/get calls
    CONTENT_DRAFT_RAW: "lb-draft-content",
    KEYS_DRAFT_RAW: "lb-draft-keys",
    REFINE_INSTRUCTIONS_RAW: "lb-refine-instructions",
    // Prefixed keys for storageKey binding on UI inputs
    CONTENT_DRAFT_KEY: "story:lb-draft-content",
    KEYS_DRAFT_KEY: "story:lb-draft-keys",
    REFINE_INSTRUCTIONS_KEY: "story:lb-refine-instructions",

    // Entry-specific IDs (for synchronization with LorebookIconButton)
    entry: (entryId: string) => ({
      CONTENT_REQ: `lb-item-${entryId}-content`,
      KEYS_REQ: `lb-item-${entryId}-keys`,
      REFINE_REQ: `lb-item-${entryId}-refine`,
    }),
  },
};
